src/main/java/com/maxmind/geoip2/DatabaseReader.java
A client with an apparently corrupt database was receiving a
ClassCastException from this code. Also removed an unnecessary `get()`.
=> Check JsonNode to ObjectNode cast

README.md, pom.xml, src/main/java/com/maxmind/geoip2/DatabaseReader.java
=> support for caching in DatabaseReader.Builder

README.md, src/main/java/com/maxmind/geoip2/DatabaseReader.java, src/main/java/com/maxmind/geoip2/WebServiceClient.java
Also, make several other minor documentation improvements.
See #91
=> Improve docs on thread-safety and object reuse

pom.xml
To avoid dependency frustration for others =)
=> added jackson-core and jackson-annotations deps

CHANGELOG.md, README.md, src/main/java/com/maxmind/geoip2/WebServiceClient.java, src/test/java/com/maxmind/geoip2/WebServiceClientTest.java
Also support the future ACCOUNT_ID_REQUIRED error code.
=> Rename userId to accountId

.travis.yml, README.md
Add Snyk integration to assess vulnerabilities in project dependencies.
=> Add Snyk integration

src/main/java/com/maxmind/geoip2/WebServiceClient.java
=> Fix WebService documentation link

.gitignore, .travis.yml, CHANGELOG.md, README.md, pom.xml, sample/Benchmark.java, src/main/java/com/maxmind/geoip2/DatabaseProvider.java, src/main/java/com/maxmind/geoip2/DatabaseReader.java, src/main/java/com/maxmind/geoip2/WebServiceClient.java, src/main/java/com/maxmind/geoip2/model/AbstractCityResponse.java, src/main/java/com/maxmind/geoip2/record/AbstractNamedRecord.java, src/test/java/com/maxmind/geoip2/DatabaseReaderTest.java, src/test/java/com/maxmind/geoip2/WebServiceClientTest.java, src/test/java/com/maxmind/geoip2/model/CountryResponseTest.java, src/test/java/com/maxmind/geoip2/model/InsightsResponseTest.java, src/test/java/com/maxmind/geoip2/model/JsonTest.java
=> Drop Java 7 support and add try methods

CHANGELOG.md, src/main/java/com/maxmind/geoip2/DatabaseReader.java, src/test/java/com/maxmind/geoip2/DatabaseReaderTest.java
Closes #132. 
This also improve the performance of the type check.
=> Allow city and country calls on all DBs with that data

CHANGELOG.md, README.md, pom.xml, src/main/java/com/maxmind/geoip2/model/IspResponse.java, src/main/java/com/maxmind/geoip2/record/Traits.java
- Fix whitespace in CHANGELOG
- [maven-release-plugin] prepare release v2.16.0
=> Release 2.16.0

CHANGELOG.md, src/main/java/com/maxmind/geoip2/model/AsnResponse.java, src/main/java/com/maxmind/geoip2/model/IspResponse.java, src/main/java/com/maxmind/geoip2/record/AbstractNamedRecord.java, src/main/java/com/maxmind/geoip2/record/City.java, src/main/java/com/maxmind/geoip2/record/Continent.java, src/main/java/com/maxmind/geoip2/record/Country.java, src/main/java/com/maxmind/geoip2/record/RepresentedCountry.java, src/main/java/com/maxmind/geoip2/record/Subdivision.java, src/main/java/com/maxmind/geoip2/record/Traits.java, src/test/java/com/maxmind/geoip2/model/CountryResponseTest.java, src/test/java/com/maxmind/geoip2/model/InsightsResponseTest.java
Also combine web service and DB model constructors in more cases.
=> Update data types to reflect DB data. Closes #178

.gitmodules, README.md, src/main/java/com/maxmind/geoip2/WebServiceClient.java, src/main/java/com/maxmind/geoip2/model/CityResponse.java, src/main/java/com/maxmind/geoip2/model/CountryResponse.java, src/main/java/com/maxmind/geoip2/model/InsightsResponse.java, src/main/java/com/maxmind/geoip2/record/Traits.java
- Update service names in documentation
- Update copyright year
=> Update service names

CHANGELOG.md, README.md, pom.xml
- [maven-release-plugin] prepare release v3.0.0
=> 3.0.0 release

CHANGELOG.md, README.md, pom.xml
- Revert "Stop using mvn to initialize/update submodule"
- Update deps
- Add release notes
- [maven-release-plugin] prepare release v3.0.2
=> Release 3.0.2

CHANGELOG.md, README.md, pom.xml, src/main/java/module-info.java
- Update maxmind-db version
- Correct module name
=> Release 4.0.0

CHANGELOG.md, README.md, src/main/java/module-info.java
- Update maxmind-db version
- Correct module name
- Disable terminal digit warning
- [maven-release-plugin] prepare release v4.0.0
- Make com.maxmind.db a transitive dependency
- Bump copyright year
=> Make maxmind-db a transitive dependency

CHANGELOG.md, README.md, pom.xml
- Update dependencies
- [maven-release-plugin] prepare release v4.0.1
=> Release 4.0.1

CHANGELOG.md, README.md, pom.xml
- Update deps
- Update maven-source-plugin goal
- [maven-release-plugin] prepare release v4.1.0
=> Release 4.1.0

CHANGELOG.md, README.md, dev-bin/release.sh, pom.xml
- **Update Maven requirement**
- **Update for path change**
- **Bump com.maxmind.db:maxmind-db from 3.1.0 to 3.1.1**
- **Add release notes**
- **update version number in README.md**
- **[maven-release-plugin] prepare release v4.2.1**
- **[maven-release-plugin] prepare for next development iteration**
=> Release 4.2.1

CHANGELOG.md, README.md, pom.xml
- **Set release date**
- **Preparing for 4.4.0**
=> Release 4.4.0
